/*
 * This file is autogenerated by cbindgen. Do not modify this file manually.
 * To regenerate this file, run:
 * ```
 * cbindgen --config cbindgen.toml --crate monero-rust --output monero-rust.h
 * ```
 * from the project root.
 *
 * For more information, see the project documentation or contact the project maintainer.
 */


#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>


/**
 * Generates an address from a mnemonic
 */
const char *generate_address(const char *mnemonic,
                             uint8_t network,
                             uint32_t account,
                             uint32_t index);

/**
 * Generates a mnemonic in the specified language
 */
const char *generate_mnemonic(uint8_t language);
